version: '3.7'
services:
  practical_django:
    image: fidelkang/s
    build:
      context: ./practical_django
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - './practical_django:/usr/src/app'
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=booktime
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - REDIS_URL=redis://redis

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=booktime
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres-data:
