version: '3.7'
services:
  practical_django:
    image: fidelkang/s
    build:
      context: ./practical_django
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - './practical_django:/usr/src/app'
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=booktime
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=booktime
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword