# Generated by Django 2.2 on 2019-04-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productname_40'),
        ('main', '0003_producttagname_40'),
    ]

    operations = [
    ]
